### ISSUE TITLE
알람 시스템에 메시지 큐 도입

### ISSUE THREAD

**Issue by attlet** [attlet/sns_project#46]
### 메시지 큐 오픈소스 도입해서 알람 개선

- 현재는 단일 서버에서 애플리케이션을 구동한다는 전제로 concurrentHashMap에 emitter를 저장하고, 알람을 구현
- 다중 서버를 고려해 메시지 큐를 도입할 필요 있음.

### 기대 효과

- 서버 확장성 : 서버를 증설하기 쉬워짐
- 비동기 메시지 처리로 병목 현상 감소
- 데이터 유실 가능성 : concurrentHashMap과 달리 서버 재시작 시 데이터 손실되지 않음 
- 메시지 처리 도중 장애 복구 : 장애 발생 시 replication 이나 파티션 등을 이용해 복구 가능

**Comment by attlet** [comment]
현재 알람 전송 방식

1. 사용자가 로그인 시 connect를 통해 sse 구독 신청. SseEmitter 생성해서 concurrentHashMap에 저장
2. 알람 발생하면, notification 엔티티 저장 후 map에서 주어진 id값을 기반으로 해당 사용자의 SseEmitter 찾음
3. SseEmitter 존재하면 해당 emitter를 이용해 알람 전송

**Comment by attlet** [comment]
### rabbitMQ 세팅

1. 설정


```
spring:
  profiles: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue: my_queue
  notification:
    broker: rabbitmq
```

build.gradle.kts에 의존성 추가

```
//rabbitMQ
	implementation("org.springframework.boot:spring-boot-starter-amqp")
```

2. producer, consumer 구현

- 인터페이스를 통해 실행환경에 따라 다른 메시지 큐 툴을 적용할 수 있도록 함.
- producer는 메시지 발생 시 rabbitMq에 메시지 전달을, consumer는 수신자들에게 메시지를 전달함

**Comment by attlet** [comment]
### redis pub/sub 세팅

1. redis 설정

```
spring:
  redis:
    host: localhost
    port: 6379
```

build.gradle.kts에 의존성 추가 

```
dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
}
```
